import type { Task, Activity, Project } from './types';

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Review project proposal',
    description: 'Go through architecture specs and finalize timeline with the product team.',
    dueDate: 'Today',
    time: '10:00 AM',
    priority: 'High priority',
    category: 'Work',
    completed: false,
  },
  {
    id: 'task-2',
    projectId: 'proj-2',
    title: 'Call Rahul',
    description: 'Sync regarding client onboarding dependencies and API milestones.',
    dueDate: 'Today',
    time: '11:30 AM',
    priority: 'Medium priority',
    category: 'Communications',
    completed: false,
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Team meeting',
    description: 'Weekly sprint alignment and cross-functional task review.',
    dueDate: 'Today',
    time: '2:00 PM',
    priority: 'Medium priority',
    category: 'Team',
    completed: false,
  },
  {
    id: 'task-4',
    projectId: null,
    title: 'Submit monthly report',
    description: 'Prepare executive summary and metrics deck for departmental review.',
    dueDate: 'Today',
    time: '4:30 PM',
    priority: 'High priority',
    category: 'Finance',
    completed: false,
  },
  {
    id: 'task-5',
    projectId: null,
    title: 'Buy groceries',
    description: 'Fresh vegetables, milk, coffee beans, and oats.',
    dueDate: 'Tomorrow',
    time: '6:00 PM',
    priority: 'Low priority',
    category: 'Personal',
    completed: false,
  },
  {
    id: 'task-6',
    projectId: null,
    title: 'Read research paper',
    description: 'Review new publication on agentic workflows and tool-calling models.',
    dueDate: 'Tomorrow',
    time: '8:00 PM',
    priority: 'Medium priority',
    category: 'Research',
    completed: false,
  },
];

export const initialActivities: Activity[] = [
  {
    id: 'act-1',
    text: 'Created task "Call Rahul"',
    timestamp: '2 minutes ago',
    type: 'created',
  },
  {
    id: 'act-2',
    text: 'Completed task "Read project brief"',
    timestamp: '1 hour ago',
    type: 'completed',
  },
  {
    id: 'act-3',
    text: 'Automation "Morning Briefing" completed',
    timestamp: '3 hours ago',
    type: 'automation',
  },
  {
    id: 'act-4',
    text: 'Created task "Submit monthly report"',
    timestamp: 'Yesterday',
    type: 'created',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    userId: null,
    name: 'Orbit Agentic Workspace',
    description: 'Build foundational task, project, and workflow orchestration architecture.',
    status: 'active',
    priority: 'high',
    createdAt: '2026-09-20T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'proj-2',
    userId: null,
    name: 'Supabase Integration & Hardening',
    description: 'Configure Row Level Security, project migrations, and resilient CRUD sync.',
    status: 'active',
    priority: 'medium',
    createdAt: '2026-09-21T12:00:00.000Z',
    updatedAt: '2026-09-21T12:00:00.000Z',
  },
  {
    id: 'proj-3',
    userId: null,
    name: 'Automated CI/CD Pipeline',
    description: 'Set up GitHub Actions to build and deploy static pages with verification.',
    status: 'completed',
    priority: 'low',
    createdAt: '2026-09-19T08:00:00.000Z',
    updatedAt: '2026-09-22T14:00:00.000Z',
  },
];
